### ISSUE TITLE
Files without a class in app directory throws exception

### ISSUE THREAD

**Issue by orjanalmen** [andyabih/laravel-to-uml#2]
ReflectionException
Class \App\Helpers does not exist

app\helpers.php isn't a class but just some few helpful functions in the global namespace. 
I think that this shouldn't throw an error, but just ignore the file.

**Comment by andyabih** [comment]
Could you let me know if it's not working for you properly? Added a few checks to handle such scenarios in v1.0.3.

**Comment by orjanalmen** [comment]
Yes, 1.0.3 fixed this!
